services:
  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
        - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - up
    depends_on:
      db:
        condition: service_healthy
    restart: no

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config/local.yml
    volumes:
      - ./config:/config
    depends_on:
      - db
      - migrate
    restart:
      unless-stopped
  
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: MY$3CR3T
    volumes:
      - ./minio-data:/data
    command:
      server /data --console-address ":9001"
    restart:
      unless-stopped

volumes:
  pgdata: