// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock.go -package=mockcodeservice
//

// Package mockcodeservice is a generated GoMock package.
package mockcodeservice

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GenerateChangePassword mocks base method.
func (m *MockService) GenerateChangePassword(ctx context.Context, userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateChangePassword", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateChangePassword indicates an expected call of GenerateChangePassword.
func (mr *MockServiceMockRecorder) GenerateChangePassword(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateChangePassword", reflect.TypeOf((*MockService)(nil).GenerateChangePassword), ctx, userID)
}

// GenerateRecoveryPassword mocks base method.
func (m *MockService) GenerateRecoveryPassword(ctx context.Context, userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRecoveryPassword", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRecoveryPassword indicates an expected call of GenerateRecoveryPassword.
func (mr *MockServiceMockRecorder) GenerateRecoveryPassword(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRecoveryPassword", reflect.TypeOf((*MockService)(nil).GenerateRecoveryPassword), ctx, userID)
}

// GenerateVerify mocks base method.
func (m *MockService) GenerateVerify(ctx context.Context, userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateVerify", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateVerify indicates an expected call of GenerateVerify.
func (mr *MockServiceMockRecorder) GenerateVerify(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateVerify", reflect.TypeOf((*MockService)(nil).GenerateVerify), ctx, userID)
}

// ValidateVerify mocks base method.
func (m *MockService) ValidateVerify(ctx context.Context, code string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateVerify", ctx, code, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateVerify indicates an expected call of ValidateVerify.
func (mr *MockServiceMockRecorder) ValidateVerify(ctx, code, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateVerify", reflect.TypeOf((*MockService)(nil).ValidateVerify), ctx, code, userID)
}
